### ISSUE TITLE
/AniSync/apiUrlTest leads to 401 error (AniList)

### ISSUE THREAD

**Issue by SadPepeIRL** [vosmiic/jellyfin-ani-sync#153] opened 2024-09-14 06:17 UTC
Describe the bug
Every time I try to test the API before configuring a client it returns a 401 (blank page in Firefox).

Logs
`2024-09-14 00:50:24.723647-05:00[00:50:24] [INF] [25] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 00:50:33.811182-05:00[00:50:33] [INF] [25] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 00:50:47.857568-05:00[00:50:47] [INF] [23] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 00:50:58.494463-05:00[00:50:58] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 00:53:03.765810-05:00[00:53:03] [INF] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:00:46.966126-05:00[01:00:46] [INF] [26] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:00:47.032796-05:00[01:00:47] [INF] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:00:57.806974-05:00[01:00:57] [INF] [26] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:01:00.128279-05:00[01:01:00] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:01:00.946939-05:00[01:01:00] [INF] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:01:14.541426-05:00[01:01:14] [INF] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:02:22.261029-05:00[01:02:22] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:07:47.924885-05:00[01:07:47] [INF] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:07:57.360044-05:00[01:07:57] [INF] [24] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:12.158207-05:00[01:08:12] [INF] [15] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:13.077174-05:00[01:08:13] [INF] [17] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:24.454277-05:00[01:08:24] [INF] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:26.696746-05:00[01:08:26] [INF] [26] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:26.849676-05:00[01:08:26] [INF] [26] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:27.048382-05:00[01:08:27] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
2024-09-14 01:08:27.216637-05:00[01:08:27] [INF] [26] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
`
Running Jellyfin on Truenas scale
![image](https://github.com/user-attachments/assets/9b43fcef-9da3-4b7d-9836-efa6bcb48dd3)

Configuration:
![image](https://github.com/user-attachments/assets/b77853a4-65bf-4f54-a7e0-a59425cbbc27)

AniList configuration:
![image](https://github.com/user-attachments/assets/0904b936-a475-4ef7-812d-013a1bd48093)
![image](https://github.com/user-attachments/assets/badaeccf-607e-4108-8bf1-9756f44a3cb2)

Firefox just goes to a blank page, Chrome gives me a 401 error page
I've tried domain, kurb IP (Truenas), the actually IP of the nas (http://10.0.0.23:8096/AniSync/apiUrlTest) and the port truenas assigned to jellyfin (http://10.0.0.23:30013/AniSync/apiUrlTest).
Any ideas?

**Comment by vosmiic** [comment] 2024-09-14 08:28
Duplicate of #152

**Closed by vosmiic** 2024-09-14 08:28 UTC
