### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by james7132** [vosmiic/jellyfin-ani-sync#60] opened 2023-03-05 15:52 UTC
Crash due to an ArgumentNullException when sending an update to my lists.

This is using 2.7.1.0 on Jellyfin 1.0.9.8.

The logs from the event:

```
2023-03-05T15:31:18.410404722Z | stderr | at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-03-05T15:31:18.410362608Z | stderr | at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-03-05T15:31:18.410316111Z | stderr | at System.Threading.QueueUserWorkItemCallback.Execute()
2023-03-05T15:31:18.410259655Z | stderr | at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
2023-03-05T15:31:18.410105261Z | stderr | at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2023-03-05T15:31:18.410057104Z | stderr | at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2023-03-05T15:31:18.410007079Z | stderr | at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
2023-03-05T15:31:18.409958100Z | stderr | at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
2023-03-05T15:31:18.409901990Z | stderr | at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2023-03-05T15:31:18.409828021Z | stderr | at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2023-03-05T15:31:18.409195905Z | stderr | Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
2023-03-05T15:31:18.409659656Z | stdout | at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-03-05T15:31:18.409597772Z | stdout | at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-03-05T15:31:18.409542187Z | stdout | at System.Threading.QueueUserWorkItemCallback.Execute()
2023-03-05T15:31:18.409486172Z | stdout | at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
2023-03-05T15:31:18.409429758Z | stdout | at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
2023-03-05T15:31:18.409369888Z | stdout | at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2023-03-05T15:31:18.409302150Z | stdout | at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
2023-03-05T15:31:18.409217512Z | stdout | at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
2023-03-05T15:31:18.409034573Z | stdout | at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2023-03-05T15:31:18.408934830Z | stdout | at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2023-03-05T15:31:18.408838661Z | stdout | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
```

**Comment by vosmiic** [comment] 2023-03-05 16:16
Hi, unfortunately that error does not return much. Does it only occur after watching that episode/movie? Or does it occur for all media?
I have wrapped the sync work in a `try` to prevent whole Jellyfin crashes, and this change will be reflected in the next release.

**Comment by james7132** [comment] 2023-03-05 18:54
I've had it happen on all media regardless of which media it was working with. Though I only really tried it on matched anime of any kind.

Is it a good idea to be suppressing the error here?

**Comment by vosmiic** [comment] 2023-03-05 20:10
>I've had it happen on all media regardless of which media it was working with. Though I only really tried it on matched anime of any kind.

Hmm okay, have you successfully authenticated the plugin? Could you try testing the authentication?
If your plugin is authenticated and the test passes, could you post your `jellyfin-ani-sync.xml` file (found in `/jellyfin/plugins/configurations`)? Please do censor all personal information first though.

>Is it a good idea to be suppressing the error here?

Well less "suppressing" and more "log the error and not cause the whole application to crash". I personally don't think a plugin should be capable of crashing the main application, and should instead log a fatal error.

**Comment by james7132** [comment] 2023-03-20 23:10
Sorry, I haven't had the time to fully investigate this. I'll try to get a set of logs within the week.

Mind cutting a patch release for this? I'd like to be able to reenable this in the meantime.

**Comment by james7132** [comment] 2023-03-20 23:13
My full config is the following. Seems borderline empty.

```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <currentlyAuthenticatingUser>00000000-0000-0000-0000-000000000000</currentlyAuthenticatingUser>
  <currentlyAuthenticatingProvider>Mal</currentlyAuthenticatingProvider>
  <watchedTickboxUpdatesProvider>false</watchedTickboxUpdatesProvider>
```

**Comment by vosmiic** [comment] 2023-03-21 18:48
>Mind cutting a patch release for this? I'd like to be able to reenable this in the meantime.

Are you hitting the issue of not being able to re-enable the plugin because its "malfunctioning"? I can send you a .dll to replace it with that should let you re-enable it if so.

>My full config is the following.

That config shows that the plugin hasn't been authenticated. I would first try authenticating the plugin with a user (if you haven't already tried). [This](https://github.com/vosmiic/jellyfin-ani-sync/wiki/Installation-&-Config#setup) guide should be able to help you.

**Comment by vosmiic** [comment] 2023-04-10 19:49
Any that have been redirected here, the crashing has been fixed in the latest version of the plugin. The plugin should now not crash the entire Jellyfin application if it hits into an issue.

As for the cause of the specific issue, I believe it is because no config has been set. In other words, you have not yet authenticated any provider for the plugin to update. Please check your configuration is correct and fully set up.

**Comment by shengdom** [comment] 2023-05-06 09:25
I am also getting this error but even earlier: When trying to authenticate. I am running Jellyfin in a docker on unraid so I've tried leaving API endpoint empty (uses the internal jellyfin IP) or filling it with the server IP (returns the following:) 
<html><body>


type | "https://tools.ietf.org/html/rfc7231#section-6.5.1"
-- | --
title | "One or more validation errors occurred."
status | 400
traceId | "00-ddc8818d4fcbcd468881d2679b4654d5-bccde88b69447552-00"
errors |  
code |  
0 | "The code field is required."


</body>
</html>

And when I try to authenticate the user I get the mentioned error from this thread either way. Any idea?

**Closed** 2023-06-02 19:25 UTC
